/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKMODEL_H
#define _MOCKMODEL_H

#include "Types.h"
#include "Model.h"

void MockModel_Init(void);
void MockModel_Destroy(void);
void MockModel_Verify(void);




#define Model_Init_Expect() Model_Init_CMockExpect(__LINE__)
void Model_Init_CMockExpect(UNITY_LINE_TYPE cmock_line);

#endif
