/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockTimerConductor.h"

typedef struct _CMOCK_TimerConductor_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_TimerConductor_Init_CALL_INSTANCE;

typedef struct _CMOCK_TimerConductor_Run_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_TimerConductor_Run_CALL_INSTANCE;

static struct MockTimerConductorInstance
{
  CMOCK_MEM_INDEX_TYPE TimerConductor_Init_CallInstance;
  CMOCK_MEM_INDEX_TYPE TimerConductor_Run_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockTimerConductor_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.TimerConductor_Init_CallInstance, cmock_line, "Function 'TimerConductor_Init' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.TimerConductor_Run_CallInstance, cmock_line, "Function 'TimerConductor_Run' called less times than expected.");
}

void MockTimerConductor_Init(void)
{
  MockTimerConductor_Destroy();
}

void MockTimerConductor_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void TimerConductor_Init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TimerConductor_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_TimerConductor_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TimerConductor_Init_CallInstance);
  Mock.TimerConductor_Init_CallInstance = CMock_Guts_MemNext(Mock.TimerConductor_Init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'TimerConductor_Init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void TimerConductor_Init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TimerConductor_Init_CALL_INSTANCE));
  CMOCK_TimerConductor_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_TimerConductor_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.TimerConductor_Init_CallInstance = CMock_Guts_MemChain(Mock.TimerConductor_Init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void TimerConductor_Run(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TimerConductor_Run_CALL_INSTANCE* cmock_call_instance = (CMOCK_TimerConductor_Run_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TimerConductor_Run_CallInstance);
  Mock.TimerConductor_Run_CallInstance = CMock_Guts_MemNext(Mock.TimerConductor_Run_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'TimerConductor_Run' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void TimerConductor_Run_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TimerConductor_Run_CALL_INSTANCE));
  CMOCK_TimerConductor_Run_CALL_INSTANCE* cmock_call_instance = (CMOCK_TimerConductor_Run_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.TimerConductor_Run_CallInstance = CMock_Guts_MemChain(Mock.TimerConductor_Run_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

