/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockTemperatureFilter.h"

typedef struct _CMOCK_TemperatureFilter_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_TemperatureFilter_Init_CALL_INSTANCE;

typedef struct _CMOCK_TemperatureFilter_GetTemperatureInCelcius_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  float ReturnVal;

} CMOCK_TemperatureFilter_GetTemperatureInCelcius_CALL_INSTANCE;

typedef struct _CMOCK_TemperatureFilter_ProcessInput_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  float Expected_temperature;

} CMOCK_TemperatureFilter_ProcessInput_CALL_INSTANCE;

static struct MockTemperatureFilterInstance
{
  CMOCK_MEM_INDEX_TYPE TemperatureFilter_Init_CallInstance;
  CMOCK_MEM_INDEX_TYPE TemperatureFilter_GetTemperatureInCelcius_CallInstance;
  CMOCK_MEM_INDEX_TYPE TemperatureFilter_ProcessInput_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockTemperatureFilter_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.TemperatureFilter_Init_CallInstance, cmock_line, "Function 'TemperatureFilter_Init' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.TemperatureFilter_GetTemperatureInCelcius_CallInstance, cmock_line, "Function 'TemperatureFilter_GetTemperatureInCelcius' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.TemperatureFilter_ProcessInput_CallInstance, cmock_line, "Function 'TemperatureFilter_ProcessInput' called less times than expected.");
}

void MockTemperatureFilter_Init(void)
{
  MockTemperatureFilter_Destroy();
}

void MockTemperatureFilter_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void TemperatureFilter_Init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TemperatureFilter_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_TemperatureFilter_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TemperatureFilter_Init_CallInstance);
  Mock.TemperatureFilter_Init_CallInstance = CMock_Guts_MemNext(Mock.TemperatureFilter_Init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'TemperatureFilter_Init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void TemperatureFilter_Init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TemperatureFilter_Init_CALL_INSTANCE));
  CMOCK_TemperatureFilter_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_TemperatureFilter_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.TemperatureFilter_Init_CallInstance = CMock_Guts_MemChain(Mock.TemperatureFilter_Init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

float TemperatureFilter_GetTemperatureInCelcius(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TemperatureFilter_GetTemperatureInCelcius_CALL_INSTANCE* cmock_call_instance = (CMOCK_TemperatureFilter_GetTemperatureInCelcius_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TemperatureFilter_GetTemperatureInCelcius_CallInstance);
  Mock.TemperatureFilter_GetTemperatureInCelcius_CallInstance = CMock_Guts_MemNext(Mock.TemperatureFilter_GetTemperatureInCelcius_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'TemperatureFilter_GetTemperatureInCelcius' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void TemperatureFilter_GetTemperatureInCelcius_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TemperatureFilter_GetTemperatureInCelcius_CALL_INSTANCE));
  CMOCK_TemperatureFilter_GetTemperatureInCelcius_CALL_INSTANCE* cmock_call_instance = (CMOCK_TemperatureFilter_GetTemperatureInCelcius_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.TemperatureFilter_GetTemperatureInCelcius_CallInstance = CMock_Guts_MemChain(Mock.TemperatureFilter_GetTemperatureInCelcius_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void TemperatureFilter_ProcessInput(float temperature)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TemperatureFilter_ProcessInput_CALL_INSTANCE* cmock_call_instance = (CMOCK_TemperatureFilter_ProcessInput_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TemperatureFilter_ProcessInput_CallInstance);
  Mock.TemperatureFilter_ProcessInput_CallInstance = CMock_Guts_MemNext(Mock.TemperatureFilter_ProcessInput_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'TemperatureFilter_ProcessInput' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_FLOAT(cmock_call_instance->Expected_temperature, temperature, cmock_line, "Function 'TemperatureFilter_ProcessInput' called with unexpected value for argument 'temperature'.");
  }
}

void CMockExpectParameters_TemperatureFilter_ProcessInput(CMOCK_TemperatureFilter_ProcessInput_CALL_INSTANCE* cmock_call_instance, float temperature)
{
  cmock_call_instance->Expected_temperature = temperature;
}

void TemperatureFilter_ProcessInput_CMockExpect(UNITY_LINE_TYPE cmock_line, float temperature)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TemperatureFilter_ProcessInput_CALL_INSTANCE));
  CMOCK_TemperatureFilter_ProcessInput_CALL_INSTANCE* cmock_call_instance = (CMOCK_TemperatureFilter_ProcessInput_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.TemperatureFilter_ProcessInput_CallInstance = CMock_Guts_MemChain(Mock.TemperatureFilter_ProcessInput_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_TemperatureFilter_ProcessInput(cmock_call_instance, temperature);
}

