/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKEXECUTOR_H
#define _MOCKEXECUTOR_H

#include "Types.h"
#include "Executor.h"

void MockExecutor_Init(void);
void MockExecutor_Destroy(void);
void MockExecutor_Verify(void);




#define Executor_Init_Expect() Executor_Init_CMockExpect(__LINE__)
void Executor_Init_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Executor_Run_ExpectAndReturn(cmock_retval) Executor_Run_CMockExpectAndReturn(__LINE__, cmock_retval)
void Executor_Run_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);

#endif
