/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKINTRINSICSWRAPPER_H
#define _MOCKINTRINSICSWRAPPER_H

#include "Types.h"
#include "IntrinsicsWrapper.h"

void MockIntrinsicsWrapper_Init(void);
void MockIntrinsicsWrapper_Destroy(void);
void MockIntrinsicsWrapper_Verify(void);




#define Interrupt_Enable_Expect() Interrupt_Enable_CMockExpect(__LINE__)
void Interrupt_Enable_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Interrupt_Disable_Expect() Interrupt_Disable_CMockExpect(__LINE__)
void Interrupt_Disable_CMockExpect(UNITY_LINE_TYPE cmock_line);

#endif
