/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockAdcHardware.h"

typedef struct _CMOCK_AdcHardware_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_AdcHardware_Init_CALL_INSTANCE;

typedef struct _CMOCK_AdcHardware_StartConversion_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_AdcHardware_StartConversion_CALL_INSTANCE;

typedef struct _CMOCK_AdcHardware_GetSampleComplete_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_AdcHardware_GetSampleComplete_CALL_INSTANCE;

typedef struct _CMOCK_AdcHardware_GetSample_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16 ReturnVal;

} CMOCK_AdcHardware_GetSample_CALL_INSTANCE;

static struct MockAdcHardwareInstance
{
  CMOCK_MEM_INDEX_TYPE AdcHardware_Init_CallInstance;
  CMOCK_MEM_INDEX_TYPE AdcHardware_StartConversion_CallInstance;
  CMOCK_MEM_INDEX_TYPE AdcHardware_GetSampleComplete_CallInstance;
  CMOCK_MEM_INDEX_TYPE AdcHardware_GetSample_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockAdcHardware_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.AdcHardware_Init_CallInstance, cmock_line, "Function 'AdcHardware_Init' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.AdcHardware_StartConversion_CallInstance, cmock_line, "Function 'AdcHardware_StartConversion' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.AdcHardware_GetSampleComplete_CallInstance, cmock_line, "Function 'AdcHardware_GetSampleComplete' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.AdcHardware_GetSample_CallInstance, cmock_line, "Function 'AdcHardware_GetSample' called less times than expected.");
}

void MockAdcHardware_Init(void)
{
  MockAdcHardware_Destroy();
}

void MockAdcHardware_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void AdcHardware_Init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_AdcHardware_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_AdcHardware_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.AdcHardware_Init_CallInstance);
  Mock.AdcHardware_Init_CallInstance = CMock_Guts_MemNext(Mock.AdcHardware_Init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'AdcHardware_Init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void AdcHardware_Init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_AdcHardware_Init_CALL_INSTANCE));
  CMOCK_AdcHardware_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_AdcHardware_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.AdcHardware_Init_CallInstance = CMock_Guts_MemChain(Mock.AdcHardware_Init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void AdcHardware_StartConversion(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_AdcHardware_StartConversion_CALL_INSTANCE* cmock_call_instance = (CMOCK_AdcHardware_StartConversion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.AdcHardware_StartConversion_CallInstance);
  Mock.AdcHardware_StartConversion_CallInstance = CMock_Guts_MemNext(Mock.AdcHardware_StartConversion_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'AdcHardware_StartConversion' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void AdcHardware_StartConversion_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_AdcHardware_StartConversion_CALL_INSTANCE));
  CMOCK_AdcHardware_StartConversion_CALL_INSTANCE* cmock_call_instance = (CMOCK_AdcHardware_StartConversion_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.AdcHardware_StartConversion_CallInstance = CMock_Guts_MemChain(Mock.AdcHardware_StartConversion_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

bool AdcHardware_GetSampleComplete(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_AdcHardware_GetSampleComplete_CALL_INSTANCE* cmock_call_instance = (CMOCK_AdcHardware_GetSampleComplete_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.AdcHardware_GetSampleComplete_CallInstance);
  Mock.AdcHardware_GetSampleComplete_CallInstance = CMock_Guts_MemNext(Mock.AdcHardware_GetSampleComplete_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'AdcHardware_GetSampleComplete' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void AdcHardware_GetSampleComplete_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_AdcHardware_GetSampleComplete_CALL_INSTANCE));
  CMOCK_AdcHardware_GetSampleComplete_CALL_INSTANCE* cmock_call_instance = (CMOCK_AdcHardware_GetSampleComplete_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.AdcHardware_GetSampleComplete_CallInstance = CMock_Guts_MemChain(Mock.AdcHardware_GetSampleComplete_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

uint16 AdcHardware_GetSample(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_AdcHardware_GetSample_CALL_INSTANCE* cmock_call_instance = (CMOCK_AdcHardware_GetSample_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.AdcHardware_GetSample_CallInstance);
  Mock.AdcHardware_GetSample_CallInstance = CMock_Guts_MemNext(Mock.AdcHardware_GetSample_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'AdcHardware_GetSample' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void AdcHardware_GetSample_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16 cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_AdcHardware_GetSample_CALL_INSTANCE));
  CMOCK_AdcHardware_GetSample_CALL_INSTANCE* cmock_call_instance = (CMOCK_AdcHardware_GetSample_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.AdcHardware_GetSample_CallInstance = CMock_Guts_MemChain(Mock.AdcHardware_GetSample_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

