/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKTASKSCHEDULER_H
#define _MOCKTASKSCHEDULER_H

#include "Types.h"
#include "TaskScheduler.h"

void MockTaskScheduler_Init(void);
void MockTaskScheduler_Destroy(void);
void MockTaskScheduler_Verify(void);




#define TaskScheduler_Init_Expect() TaskScheduler_Init_CMockExpect(__LINE__)
void TaskScheduler_Init_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define TaskScheduler_Update_Expect(time) TaskScheduler_Update_CMockExpect(__LINE__, time)
void TaskScheduler_Update_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32 time);
#define TaskScheduler_DoUsart_ExpectAndReturn(cmock_retval) TaskScheduler_DoUsart_CMockExpectAndReturn(__LINE__, cmock_retval)
void TaskScheduler_DoUsart_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define TaskScheduler_DoAdc_ExpectAndReturn(cmock_retval) TaskScheduler_DoAdc_CMockExpectAndReturn(__LINE__, cmock_retval)
void TaskScheduler_DoAdc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);

#endif
