/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockUsartConductor.h"

typedef struct _CMOCK_UsartConductor_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_UsartConductor_Init_CALL_INSTANCE;

typedef struct _CMOCK_UsartConductor_Run_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_UsartConductor_Run_CALL_INSTANCE;

static struct MockUsartConductorInstance
{
  CMOCK_MEM_INDEX_TYPE UsartConductor_Init_CallInstance;
  CMOCK_MEM_INDEX_TYPE UsartConductor_Run_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockUsartConductor_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.UsartConductor_Init_CallInstance, cmock_line, "Function 'UsartConductor_Init' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.UsartConductor_Run_CallInstance, cmock_line, "Function 'UsartConductor_Run' called less times than expected.");
}

void MockUsartConductor_Init(void)
{
  MockUsartConductor_Destroy();
}

void MockUsartConductor_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void UsartConductor_Init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_UsartConductor_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_UsartConductor_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.UsartConductor_Init_CallInstance);
  Mock.UsartConductor_Init_CallInstance = CMock_Guts_MemNext(Mock.UsartConductor_Init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'UsartConductor_Init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void UsartConductor_Init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UsartConductor_Init_CALL_INSTANCE));
  CMOCK_UsartConductor_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_UsartConductor_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.UsartConductor_Init_CallInstance = CMock_Guts_MemChain(Mock.UsartConductor_Init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void UsartConductor_Run(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_UsartConductor_Run_CALL_INSTANCE* cmock_call_instance = (CMOCK_UsartConductor_Run_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.UsartConductor_Run_CallInstance);
  Mock.UsartConductor_Run_CallInstance = CMock_Guts_MemNext(Mock.UsartConductor_Run_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'UsartConductor_Run' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void UsartConductor_Run_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_UsartConductor_Run_CALL_INSTANCE));
  CMOCK_UsartConductor_Run_CALL_INSTANCE* cmock_call_instance = (CMOCK_UsartConductor_Run_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.UsartConductor_Run_CallInstance = CMock_Guts_MemChain(Mock.UsartConductor_Run_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

