/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKTEMPERATUREFILTER_H
#define _MOCKTEMPERATUREFILTER_H

#include "Types.h"
#include "TemperatureFilter.h"

void MockTemperatureFilter_Init(void);
void MockTemperatureFilter_Destroy(void);
void MockTemperatureFilter_Verify(void);




#define TemperatureFilter_Init_Expect() TemperatureFilter_Init_CMockExpect(__LINE__)
void TemperatureFilter_Init_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define TemperatureFilter_GetTemperatureInCelcius_ExpectAndReturn(cmock_retval) TemperatureFilter_GetTemperatureInCelcius_CMockExpectAndReturn(__LINE__, cmock_retval)
void TemperatureFilter_GetTemperatureInCelcius_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, float cmock_to_return);
#define TemperatureFilter_ProcessInput_Expect(temperature) TemperatureFilter_ProcessInput_CMockExpect(__LINE__, temperature)
void TemperatureFilter_ProcessInput_CMockExpect(UNITY_LINE_TYPE cmock_line, float temperature);

#endif
