/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockTaskScheduler.h"

typedef struct _CMOCK_TaskScheduler_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_TaskScheduler_Init_CALL_INSTANCE;

typedef struct _CMOCK_TaskScheduler_Update_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint32 Expected_time;

} CMOCK_TaskScheduler_Update_CALL_INSTANCE;

typedef struct _CMOCK_TaskScheduler_DoUsart_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_TaskScheduler_DoUsart_CALL_INSTANCE;

typedef struct _CMOCK_TaskScheduler_DoAdc_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_TaskScheduler_DoAdc_CALL_INSTANCE;

static struct MockTaskSchedulerInstance
{
  CMOCK_MEM_INDEX_TYPE TaskScheduler_Init_CallInstance;
  CMOCK_MEM_INDEX_TYPE TaskScheduler_Update_CallInstance;
  CMOCK_MEM_INDEX_TYPE TaskScheduler_DoUsart_CallInstance;
  CMOCK_MEM_INDEX_TYPE TaskScheduler_DoAdc_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockTaskScheduler_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.TaskScheduler_Init_CallInstance, cmock_line, "Function 'TaskScheduler_Init' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.TaskScheduler_Update_CallInstance, cmock_line, "Function 'TaskScheduler_Update' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.TaskScheduler_DoUsart_CallInstance, cmock_line, "Function 'TaskScheduler_DoUsart' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.TaskScheduler_DoAdc_CallInstance, cmock_line, "Function 'TaskScheduler_DoAdc' called less times than expected.");
}

void MockTaskScheduler_Init(void)
{
  MockTaskScheduler_Destroy();
}

void MockTaskScheduler_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void TaskScheduler_Init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TaskScheduler_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_TaskScheduler_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TaskScheduler_Init_CallInstance);
  Mock.TaskScheduler_Init_CallInstance = CMock_Guts_MemNext(Mock.TaskScheduler_Init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'TaskScheduler_Init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void TaskScheduler_Init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TaskScheduler_Init_CALL_INSTANCE));
  CMOCK_TaskScheduler_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_TaskScheduler_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.TaskScheduler_Init_CallInstance = CMock_Guts_MemChain(Mock.TaskScheduler_Init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void TaskScheduler_Update(uint32 time)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TaskScheduler_Update_CALL_INSTANCE* cmock_call_instance = (CMOCK_TaskScheduler_Update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TaskScheduler_Update_CallInstance);
  Mock.TaskScheduler_Update_CallInstance = CMock_Guts_MemNext(Mock.TaskScheduler_Update_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'TaskScheduler_Update' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_HEX32(cmock_call_instance->Expected_time, time, cmock_line, "Function 'TaskScheduler_Update' called with unexpected value for argument 'time'.");
  }
}

void CMockExpectParameters_TaskScheduler_Update(CMOCK_TaskScheduler_Update_CALL_INSTANCE* cmock_call_instance, uint32 time)
{
  cmock_call_instance->Expected_time = time;
}

void TaskScheduler_Update_CMockExpect(UNITY_LINE_TYPE cmock_line, uint32 time)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TaskScheduler_Update_CALL_INSTANCE));
  CMOCK_TaskScheduler_Update_CALL_INSTANCE* cmock_call_instance = (CMOCK_TaskScheduler_Update_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.TaskScheduler_Update_CallInstance = CMock_Guts_MemChain(Mock.TaskScheduler_Update_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_TaskScheduler_Update(cmock_call_instance, time);
}

bool TaskScheduler_DoUsart(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TaskScheduler_DoUsart_CALL_INSTANCE* cmock_call_instance = (CMOCK_TaskScheduler_DoUsart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TaskScheduler_DoUsart_CallInstance);
  Mock.TaskScheduler_DoUsart_CallInstance = CMock_Guts_MemNext(Mock.TaskScheduler_DoUsart_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'TaskScheduler_DoUsart' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void TaskScheduler_DoUsart_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TaskScheduler_DoUsart_CALL_INSTANCE));
  CMOCK_TaskScheduler_DoUsart_CALL_INSTANCE* cmock_call_instance = (CMOCK_TaskScheduler_DoUsart_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.TaskScheduler_DoUsart_CallInstance = CMock_Guts_MemChain(Mock.TaskScheduler_DoUsart_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

bool TaskScheduler_DoAdc(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_TaskScheduler_DoAdc_CALL_INSTANCE* cmock_call_instance = (CMOCK_TaskScheduler_DoAdc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.TaskScheduler_DoAdc_CallInstance);
  Mock.TaskScheduler_DoAdc_CallInstance = CMock_Guts_MemNext(Mock.TaskScheduler_DoAdc_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'TaskScheduler_DoAdc' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void TaskScheduler_DoAdc_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_TaskScheduler_DoAdc_CALL_INSTANCE));
  CMOCK_TaskScheduler_DoAdc_CALL_INSTANCE* cmock_call_instance = (CMOCK_TaskScheduler_DoAdc_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.TaskScheduler_DoAdc_CallInstance = CMock_Guts_MemChain(Mock.TaskScheduler_DoAdc_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

