/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKADCHARDWARE_H
#define _MOCKADCHARDWARE_H

#include "Types.h"
#include "AdcHardware.h"

void MockAdcHardware_Init(void);
void MockAdcHardware_Destroy(void);
void MockAdcHardware_Verify(void);




#define AdcHardware_Init_Expect() AdcHardware_Init_CMockExpect(__LINE__)
void AdcHardware_Init_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define AdcHardware_StartConversion_Expect() AdcHardware_StartConversion_CMockExpect(__LINE__)
void AdcHardware_StartConversion_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define AdcHardware_GetSampleComplete_ExpectAndReturn(cmock_retval) AdcHardware_GetSampleComplete_CMockExpectAndReturn(__LINE__, cmock_retval)
void AdcHardware_GetSampleComplete_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define AdcHardware_GetSample_ExpectAndReturn(cmock_retval) AdcHardware_GetSample_CMockExpectAndReturn(__LINE__, cmock_retval)
void AdcHardware_GetSample_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint16 cmock_to_return);

#endif
