/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKADCMODEL_H
#define _MOCKADCMODEL_H

#include "Types.h"
#include "AdcModel.h"

void MockAdcModel_Init(void);
void MockAdcModel_Destroy(void);
void MockAdcModel_Verify(void);




#define AdcModel_DoGetSample_ExpectAndReturn(cmock_retval) AdcModel_DoGetSample_CMockExpectAndReturn(__LINE__, cmock_retval)
void AdcModel_DoGetSample_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define AdcModel_ProcessInput_Expect(millivolts) AdcModel_ProcessInput_CMockExpect(__LINE__, millivolts)
void AdcModel_ProcessInput_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16 millivolts);
#define AdcModel_DoNothingExceptTestASpecialType_ExpectAndReturn(ExampleStruct, cmock_retval) AdcModel_DoNothingExceptTestASpecialType_CMockExpectAndReturn(__LINE__, ExampleStruct, cmock_retval)
void AdcModel_DoNothingExceptTestASpecialType_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, EXAMPLE_STRUCT_T ExampleStruct, bool cmock_to_return);
#define AdModel_DoNothingExceptTestPointers_ExpectAndReturn(pExample, cmock_retval) AdModel_DoNothingExceptTestPointers_CMockExpectAndReturn(__LINE__, pExample, cmock_retval)
void AdModel_DoNothingExceptTestPointers_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32* pExample, bool cmock_to_return);
#define AdcModel_DoNothingExceptReturnASpecialType_ExpectAndReturn(cmock_retval) AdcModel_DoNothingExceptReturnASpecialType_CMockExpectAndReturn(__LINE__, cmock_retval)
void AdcModel_DoNothingExceptReturnASpecialType_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, EXAMPLE_STRUCT_T cmock_to_return);

#endif
