/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockIntrinsicsWrapper.h"

typedef struct _CMOCK_Interrupt_Enable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_Interrupt_Enable_CALL_INSTANCE;

typedef struct _CMOCK_Interrupt_Disable_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_Interrupt_Disable_CALL_INSTANCE;

static struct MockIntrinsicsWrapperInstance
{
  CMOCK_MEM_INDEX_TYPE Interrupt_Enable_CallInstance;
  CMOCK_MEM_INDEX_TYPE Interrupt_Disable_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockIntrinsicsWrapper_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Interrupt_Enable_CallInstance, cmock_line, "Function 'Interrupt_Enable' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Interrupt_Disable_CallInstance, cmock_line, "Function 'Interrupt_Disable' called less times than expected.");
}

void MockIntrinsicsWrapper_Init(void)
{
  MockIntrinsicsWrapper_Destroy();
}

void MockIntrinsicsWrapper_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void Interrupt_Enable(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Interrupt_Enable_CALL_INSTANCE* cmock_call_instance = (CMOCK_Interrupt_Enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Interrupt_Enable_CallInstance);
  Mock.Interrupt_Enable_CallInstance = CMock_Guts_MemNext(Mock.Interrupt_Enable_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'Interrupt_Enable' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void Interrupt_Enable_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Interrupt_Enable_CALL_INSTANCE));
  CMOCK_Interrupt_Enable_CALL_INSTANCE* cmock_call_instance = (CMOCK_Interrupt_Enable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Interrupt_Enable_CallInstance = CMock_Guts_MemChain(Mock.Interrupt_Enable_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

void Interrupt_Disable(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Interrupt_Disable_CALL_INSTANCE* cmock_call_instance = (CMOCK_Interrupt_Disable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Interrupt_Disable_CallInstance);
  Mock.Interrupt_Disable_CallInstance = CMock_Guts_MemNext(Mock.Interrupt_Disable_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'Interrupt_Disable' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void Interrupt_Disable_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Interrupt_Disable_CALL_INSTANCE));
  CMOCK_Interrupt_Disable_CALL_INSTANCE* cmock_call_instance = (CMOCK_Interrupt_Disable_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Interrupt_Disable_CallInstance = CMock_Guts_MemChain(Mock.Interrupt_Disable_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

