/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKADCCONDUCTOR_H
#define _MOCKADCCONDUCTOR_H

#include "Types.h"
#include "AdcConductor.h"

void MockAdcConductor_Init(void);
void MockAdcConductor_Destroy(void);
void MockAdcConductor_Verify(void);




#define AdcConductor_Init_Expect() AdcConductor_Init_CMockExpect(__LINE__)
void AdcConductor_Init_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define AdcConductor_Run_Expect() AdcConductor_Run_CMockExpect(__LINE__)
void AdcConductor_Run_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define AdcConductor_JustHereToTest_ExpectAndReturn(cmock_retval) AdcConductor_JustHereToTest_CMockExpectAndReturn(__LINE__, cmock_retval)
void AdcConductor_JustHereToTest_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define AdcConductor_AlsoHereToTest_ExpectAndReturn(cmock_retval) AdcConductor_AlsoHereToTest_CMockExpectAndReturn(__LINE__, cmock_retval)
void AdcConductor_AlsoHereToTest_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);
#define AdcConductor_YetAnotherTest_ExpectAndReturn(cmock_retval) AdcConductor_YetAnotherTest_CMockExpectAndReturn(__LINE__, cmock_retval)
void AdcConductor_YetAnotherTest_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return);

#endif
