/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockModel.h"

typedef struct _CMOCK_Model_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_Model_Init_CALL_INSTANCE;

static struct MockModelInstance
{
  CMOCK_MEM_INDEX_TYPE Model_Init_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockModel_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Model_Init_CallInstance, cmock_line, "Function 'Model_Init' called less times than expected.");
}

void MockModel_Init(void)
{
  MockModel_Destroy();
}

void MockModel_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void Model_Init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Model_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_Model_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Model_Init_CallInstance);
  Mock.Model_Init_CallInstance = CMock_Guts_MemNext(Mock.Model_Init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'Model_Init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void Model_Init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Model_Init_CALL_INSTANCE));
  CMOCK_Model_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_Model_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Model_Init_CallInstance = CMock_Guts_MemChain(Mock.Model_Init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

