/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockAdcModel.h"

typedef struct _CMOCK_AdcModel_DoGetSample_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_AdcModel_DoGetSample_CALL_INSTANCE;

typedef struct _CMOCK_AdcModel_ProcessInput_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  uint16 Expected_millivolts;

} CMOCK_AdcModel_ProcessInput_CALL_INSTANCE;

typedef struct _CMOCK_AdcModel_DoNothingExceptTestASpecialType_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  EXAMPLE_STRUCT_T Expected_ExampleStruct;

} CMOCK_AdcModel_DoNothingExceptTestASpecialType_CALL_INSTANCE;

typedef struct _CMOCK_AdModel_DoNothingExceptTestPointers_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;
  uint32* Expected_pExample;

} CMOCK_AdModel_DoNothingExceptTestPointers_CALL_INSTANCE;

typedef struct _CMOCK_AdcModel_DoNothingExceptReturnASpecialType_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  EXAMPLE_STRUCT_T ReturnVal;

} CMOCK_AdcModel_DoNothingExceptReturnASpecialType_CALL_INSTANCE;

static struct MockAdcModelInstance
{
  CMOCK_MEM_INDEX_TYPE AdcModel_DoGetSample_CallInstance;
  CMOCK_MEM_INDEX_TYPE AdcModel_ProcessInput_CallInstance;
  CMOCK_MEM_INDEX_TYPE AdcModel_DoNothingExceptTestASpecialType_CallInstance;
  CMOCK_MEM_INDEX_TYPE AdModel_DoNothingExceptTestPointers_CallInstance;
  CMOCK_MEM_INDEX_TYPE AdcModel_DoNothingExceptReturnASpecialType_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockAdcModel_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.AdcModel_DoGetSample_CallInstance, cmock_line, "Function 'AdcModel_DoGetSample' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.AdcModel_ProcessInput_CallInstance, cmock_line, "Function 'AdcModel_ProcessInput' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.AdcModel_DoNothingExceptTestASpecialType_CallInstance, cmock_line, "Function 'AdcModel_DoNothingExceptTestASpecialType' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.AdModel_DoNothingExceptTestPointers_CallInstance, cmock_line, "Function 'AdModel_DoNothingExceptTestPointers' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.AdcModel_DoNothingExceptReturnASpecialType_CallInstance, cmock_line, "Function 'AdcModel_DoNothingExceptReturnASpecialType' called less times than expected.");
}

void MockAdcModel_Init(void)
{
  MockAdcModel_Destroy();
}

void MockAdcModel_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

bool AdcModel_DoGetSample(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_AdcModel_DoGetSample_CALL_INSTANCE* cmock_call_instance = (CMOCK_AdcModel_DoGetSample_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.AdcModel_DoGetSample_CallInstance);
  Mock.AdcModel_DoGetSample_CallInstance = CMock_Guts_MemNext(Mock.AdcModel_DoGetSample_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'AdcModel_DoGetSample' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void AdcModel_DoGetSample_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_AdcModel_DoGetSample_CALL_INSTANCE));
  CMOCK_AdcModel_DoGetSample_CALL_INSTANCE* cmock_call_instance = (CMOCK_AdcModel_DoGetSample_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.AdcModel_DoGetSample_CallInstance = CMock_Guts_MemChain(Mock.AdcModel_DoGetSample_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

void AdcModel_ProcessInput(uint16 millivolts)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_AdcModel_ProcessInput_CALL_INSTANCE* cmock_call_instance = (CMOCK_AdcModel_ProcessInput_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.AdcModel_ProcessInput_CallInstance);
  Mock.AdcModel_ProcessInput_CallInstance = CMock_Guts_MemNext(Mock.AdcModel_ProcessInput_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'AdcModel_ProcessInput' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_HEX16(cmock_call_instance->Expected_millivolts, millivolts, cmock_line, "Function 'AdcModel_ProcessInput' called with unexpected value for argument 'millivolts'.");
  }
}

void CMockExpectParameters_AdcModel_ProcessInput(CMOCK_AdcModel_ProcessInput_CALL_INSTANCE* cmock_call_instance, uint16 millivolts)
{
  cmock_call_instance->Expected_millivolts = millivolts;
}

void AdcModel_ProcessInput_CMockExpect(UNITY_LINE_TYPE cmock_line, uint16 millivolts)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_AdcModel_ProcessInput_CALL_INSTANCE));
  CMOCK_AdcModel_ProcessInput_CALL_INSTANCE* cmock_call_instance = (CMOCK_AdcModel_ProcessInput_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.AdcModel_ProcessInput_CallInstance = CMock_Guts_MemChain(Mock.AdcModel_ProcessInput_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_AdcModel_ProcessInput(cmock_call_instance, millivolts);
}

bool AdcModel_DoNothingExceptTestASpecialType(EXAMPLE_STRUCT_T ExampleStruct)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_AdcModel_DoNothingExceptTestASpecialType_CALL_INSTANCE* cmock_call_instance = (CMOCK_AdcModel_DoNothingExceptTestASpecialType_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.AdcModel_DoNothingExceptTestASpecialType_CallInstance);
  Mock.AdcModel_DoNothingExceptTestASpecialType_CallInstance = CMock_Guts_MemNext(Mock.AdcModel_DoNothingExceptTestASpecialType_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'AdcModel_DoNothingExceptTestASpecialType' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    UNITY_TEST_ASSERT_EQUAL_MEMORY((void*)(&cmock_call_instance->Expected_ExampleStruct), (void*)(&ExampleStruct), sizeof(EXAMPLE_STRUCT_T), cmock_line, "Function 'AdcModel_DoNothingExceptTestASpecialType' called with unexpected value for argument 'ExampleStruct'.");
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_AdcModel_DoNothingExceptTestASpecialType(CMOCK_AdcModel_DoNothingExceptTestASpecialType_CALL_INSTANCE* cmock_call_instance, EXAMPLE_STRUCT_T ExampleStruct)
{
  memcpy(&cmock_call_instance->Expected_ExampleStruct, &ExampleStruct, sizeof(EXAMPLE_STRUCT_T));
}

void AdcModel_DoNothingExceptTestASpecialType_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, EXAMPLE_STRUCT_T ExampleStruct, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_AdcModel_DoNothingExceptTestASpecialType_CALL_INSTANCE));
  CMOCK_AdcModel_DoNothingExceptTestASpecialType_CALL_INSTANCE* cmock_call_instance = (CMOCK_AdcModel_DoNothingExceptTestASpecialType_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.AdcModel_DoNothingExceptTestASpecialType_CallInstance = CMock_Guts_MemChain(Mock.AdcModel_DoNothingExceptTestASpecialType_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_AdcModel_DoNothingExceptTestASpecialType(cmock_call_instance, ExampleStruct);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

bool AdModel_DoNothingExceptTestPointers(uint32* pExample)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_AdModel_DoNothingExceptTestPointers_CALL_INSTANCE* cmock_call_instance = (CMOCK_AdModel_DoNothingExceptTestPointers_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.AdModel_DoNothingExceptTestPointers_CallInstance);
  Mock.AdModel_DoNothingExceptTestPointers_CallInstance = CMock_Guts_MemNext(Mock.AdModel_DoNothingExceptTestPointers_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'AdModel_DoNothingExceptTestPointers' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  {
    if (cmock_call_instance->Expected_pExample == NULL)
      { UNITY_TEST_ASSERT_NULL(pExample, cmock_line, "Expected NULL. Function 'AdModel_DoNothingExceptTestPointers' called with unexpected value for argument 'pExample'."); }
    else
      { UNITY_TEST_ASSERT_EQUAL_HEX32_ARRAY(cmock_call_instance->Expected_pExample, pExample, 1, cmock_line, "Function 'AdModel_DoNothingExceptTestPointers' called with unexpected value for argument 'pExample'."); }
  }
  return cmock_call_instance->ReturnVal;
}

void CMockExpectParameters_AdModel_DoNothingExceptTestPointers(CMOCK_AdModel_DoNothingExceptTestPointers_CALL_INSTANCE* cmock_call_instance, uint32* pExample)
{
  cmock_call_instance->Expected_pExample = pExample;
}

void AdModel_DoNothingExceptTestPointers_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, uint32* pExample, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_AdModel_DoNothingExceptTestPointers_CALL_INSTANCE));
  CMOCK_AdModel_DoNothingExceptTestPointers_CALL_INSTANCE* cmock_call_instance = (CMOCK_AdModel_DoNothingExceptTestPointers_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.AdModel_DoNothingExceptTestPointers_CallInstance = CMock_Guts_MemChain(Mock.AdModel_DoNothingExceptTestPointers_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  CMockExpectParameters_AdModel_DoNothingExceptTestPointers(cmock_call_instance, pExample);
  cmock_call_instance->ReturnVal = cmock_to_return;
}

EXAMPLE_STRUCT_T AdcModel_DoNothingExceptReturnASpecialType(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_AdcModel_DoNothingExceptReturnASpecialType_CALL_INSTANCE* cmock_call_instance = (CMOCK_AdcModel_DoNothingExceptReturnASpecialType_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.AdcModel_DoNothingExceptReturnASpecialType_CallInstance);
  Mock.AdcModel_DoNothingExceptReturnASpecialType_CallInstance = CMock_Guts_MemNext(Mock.AdcModel_DoNothingExceptReturnASpecialType_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'AdcModel_DoNothingExceptReturnASpecialType' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void AdcModel_DoNothingExceptReturnASpecialType_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, EXAMPLE_STRUCT_T cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_AdcModel_DoNothingExceptReturnASpecialType_CALL_INSTANCE));
  CMOCK_AdcModel_DoNothingExceptReturnASpecialType_CALL_INSTANCE* cmock_call_instance = (CMOCK_AdcModel_DoNothingExceptReturnASpecialType_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.AdcModel_DoNothingExceptReturnASpecialType_CallInstance = CMock_Guts_MemChain(Mock.AdcModel_DoNothingExceptReturnASpecialType_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  memcpy(&cmock_call_instance->ReturnVal, &cmock_to_return, sizeof(EXAMPLE_STRUCT_T));
}

