/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKUSARTCONDUCTOR_H
#define _MOCKUSARTCONDUCTOR_H

#include "Types.h"
#include "UsartConductor.h"

void MockUsartConductor_Init(void);
void MockUsartConductor_Destroy(void);
void MockUsartConductor_Verify(void);




#define UsartConductor_Init_Expect() UsartConductor_Init_CMockExpect(__LINE__)
void UsartConductor_Init_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define UsartConductor_Run_Expect() UsartConductor_Run_CMockExpect(__LINE__)
void UsartConductor_Run_CMockExpect(UNITY_LINE_TYPE cmock_line);

#endif
