/* AUTOGENERATED FILE. DO NOT EDIT. */
#ifndef _MOCKADCHARDWARECONFIGURATOR_H
#define _MOCKADCHARDWARECONFIGURATOR_H

#include "Types.h"
#include "AdcHardwareConfigurator.h"

void MockAdcHardwareConfigurator_Init(void);
void MockAdcHardwareConfigurator_Destroy(void);
void MockAdcHardwareConfigurator_Verify(void);




#define Adc_Reset_Expect() Adc_Reset_CMockExpect(__LINE__)
void Adc_Reset_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Adc_ConfigureMode_Expect() Adc_ConfigureMode_CMockExpect(__LINE__)
void Adc_ConfigureMode_CMockExpect(UNITY_LINE_TYPE cmock_line);
#define Adc_EnableTemperatureChannel_Expect() Adc_EnableTemperatureChannel_CMockExpect(__LINE__)
void Adc_EnableTemperatureChannel_CMockExpect(UNITY_LINE_TYPE cmock_line);

#endif
