/* AUTOGENERATED FILE. DO NOT EDIT. */
#include <string.h>
#include <stdlib.h>
#include <setjmp.h>
#include "unity.h"
#include "cmock.h"
#include "MockExecutor.h"

typedef struct _CMOCK_Executor_Init_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;

} CMOCK_Executor_Init_CALL_INSTANCE;

typedef struct _CMOCK_Executor_Run_CALL_INSTANCE
{
  UNITY_LINE_TYPE LineNumber;
  bool ReturnVal;

} CMOCK_Executor_Run_CALL_INSTANCE;

static struct MockExecutorInstance
{
  CMOCK_MEM_INDEX_TYPE Executor_Init_CallInstance;
  CMOCK_MEM_INDEX_TYPE Executor_Run_CallInstance;
} Mock;

extern jmp_buf AbortFrame;

void MockExecutor_Verify(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Executor_Init_CallInstance, cmock_line, "Function 'Executor_Init' called less times than expected.");
  UNITY_TEST_ASSERT(CMOCK_GUTS_NONE == Mock.Executor_Run_CallInstance, cmock_line, "Function 'Executor_Run' called less times than expected.");
}

void MockExecutor_Init(void)
{
  MockExecutor_Destroy();
}

void MockExecutor_Destroy(void)
{
  CMock_Guts_MemFreeAll();
  memset(&Mock, 0, sizeof(Mock));
}

void Executor_Init(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Executor_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_Executor_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Executor_Init_CallInstance);
  Mock.Executor_Init_CallInstance = CMock_Guts_MemNext(Mock.Executor_Init_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'Executor_Init' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
}

void Executor_Init_CMockExpect(UNITY_LINE_TYPE cmock_line)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Executor_Init_CALL_INSTANCE));
  CMOCK_Executor_Init_CALL_INSTANCE* cmock_call_instance = (CMOCK_Executor_Init_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Executor_Init_CallInstance = CMock_Guts_MemChain(Mock.Executor_Init_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
}

bool Executor_Run(void)
{
  UNITY_LINE_TYPE cmock_line = TEST_LINE_NUM;
  CMOCK_Executor_Run_CALL_INSTANCE* cmock_call_instance = (CMOCK_Executor_Run_CALL_INSTANCE*)CMock_Guts_GetAddressFor(Mock.Executor_Run_CallInstance);
  Mock.Executor_Run_CallInstance = CMock_Guts_MemNext(Mock.Executor_Run_CallInstance);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "Function 'Executor_Run' called more times than expected.");
  cmock_line = cmock_call_instance->LineNumber;
  return cmock_call_instance->ReturnVal;
}

void Executor_Run_CMockExpectAndReturn(UNITY_LINE_TYPE cmock_line, bool cmock_to_return)
{
  CMOCK_MEM_INDEX_TYPE cmock_guts_index = CMock_Guts_MemNew(sizeof(CMOCK_Executor_Run_CALL_INSTANCE));
  CMOCK_Executor_Run_CALL_INSTANCE* cmock_call_instance = (CMOCK_Executor_Run_CALL_INSTANCE*)CMock_Guts_GetAddressFor(cmock_guts_index);
  UNITY_TEST_ASSERT_NOT_NULL(cmock_call_instance, cmock_line, "CMock has run out of memory. Please allocate more.");
  Mock.Executor_Run_CallInstance = CMock_Guts_MemChain(Mock.Executor_Run_CallInstance, cmock_guts_index);
  cmock_call_instance->LineNumber = cmock_line;
  cmock_call_instance->ReturnVal = cmock_to_return;
}

